### ISSUE TITLE
Wednesday Lunch

### ISSUE THREAD

**Issue by brianamarie** [githubschool/fra-14#2]
[The menu can be found here](http://pizzeria-metaponto.de/wp-content/uploads/2017/01/FlyerMetaponto_11-2016_WebVersion.pdf). Please comment with your lunch number and your name 🍕 🍝 

<img width="855" alt="screen shot 2018-03-13 at 9 52 39 am" src="https://user-images.githubusercontent.com/9906718/37331474-5674f292-26a4-11e8-8471-45326272e463.png">
<img width="858" alt="screen shot 2018-03-13 at 9 52 56 am" src="https://user-images.githubusercontent.com/9906718/37331476-57705416-26a4-11e8-9637-6579b810d105.png">

**Comment by schasan** [comment]
#2 Pizza Funghi
#26 Insalata Mista

**Comment by zs010** [comment]
#12 Pizza Vegetaria - Frank

**Comment by brianamarie** [comment]
85 Briana 🍝

**Comment by ghost** [comment]
**1x 67 Tagliatelle al Salmone** for Andreas
**1x 7 Spezial** for Thomas

**Comment by joolka** [comment]
64 Gnocchi  alla Chef (Joachim O.)
26 Insalata Mista

**Comment by it814** [comment]
#36 Spaghetti B.

**Comment by reda134** [comment]
17 Hawai
17 Hawai
22 4 Formaggi

**Comment by beardofedu** [comment]
17 Hawaii - Matt

**Comment by rj529jonesy** [comment]
68 Tagliatelle for Ian please

**Comment by cvoica** [comment]
#27 - Insalata Italia for Cristian Voica

**Comment by albechr** [comment]
10 siciliana

**Comment by beardofedu** [comment]
35 Spaghetti Pomodoro

**Comment by wt818** [comment]
48 Rigatoni 4 Formaggi -> 
Claus Berty

**Comment by sathariel74** [comment]
7 Thorsten

**Comment by arislan82** [comment]
#5 + onions / Florian

**Comment by brianamarie** [comment]
85 Humpf

**Comment by nikoton** [comment]
16 Rucola - Toni

**Comment by zoltancsonka** [comment]
#23 Pizza Mozzarella for Zoltán

**Comment by beardofedu** [comment]
@brianamarie all good upstairs , order when your group is good to go

**Comment by brianamarie** [comment]
101

**Comment by nathpree** [comment]
Today is our GitHub training at Fintech

**Comment by harry-humpf** [comment]
hi

**Comment by Sheetanshu-gautam** [comment]
hello

**Comment by mmsousa** [comment]
53 - Penne al Salmone
