### ISSUE TITLE
Thursday Lunch

### ISSUE THREAD

**Issue by beardofedu** [githubschool/fra-14#20]
[The menu can be found here](http://pizzeria-metaponto.de/wp-content/uploads/2017/01/FlyerMetaponto_11-2016_WebVersion.pdf). Please comment with your lunch number and your name 🍕 🍝

**Comment by beardofedu** [comment]
@brianamarie ordering issue for tomorrow's lunch

**Comment by brianamarie** [comment]
Briana 23

**Comment by wt818** [comment]
62 Gnocchi Gorgonzola -> Claus

**Comment by sathariel74** [comment]
42 + 28 -> Thorsten

**Comment by rj529jonesy** [comment]
22 Quattro for Ian

**Comment by Sheetanshu-gautam** [comment]
12 vegetaria Pizza

**Comment by albechr** [comment]
16 rucola (christian)

**Comment by harry-humpf** [comment]
23 - una pizza mozzarella per Axel

**Comment by it814** [comment]
#23 for peter

**Comment by ghost** [comment]
- **67 - Tagliatelle al Salmone** for Andreas
- **7 - Pizza Spezial** for Thomas

**Comment by schasan** [comment]
#27 Insalata Italia
#49 Rigatoni di Ponto

**Comment by zs010** [comment]
87 for Frank

**Comment by reda134** [comment]
29 - Insalata Ponto (Jürgen)
34 - Insalata Di Mare ( Reda ) 
34 ist aus

**Comment by zoltancsonka** [comment]
16 Pizza Rucola for Zoltán

**Comment by nikoton** [comment]
26 and 64 -> ToNi

**Comment by fabtagon** [comment]
49

**Comment by joolka** [comment]
45 Spaghetti Rucola -> Joachim

**Comment by nathpree** [comment]
101 + 87 ---> Preetam

**Comment by beardofedu** [comment]
17 Matt

**Comment by arislan82** [comment]
27 + 62 / Florian

**Comment by cvoica** [comment]
27 - Cristian Voica

**Comment by albechr** [comment]
85 dazu
