### ISSUE TITLE
"Your account has been flagged."

### ISSUE THREAD

**Issue by ghost** [githubschool/fra-14#8]
@beardofedu 
My account is "flagged".
It says: 

> Your account has been flagged.
> Because of that, your profile is hidden from the public. If you believe this is a mistake, contact support to have your account status reviewed. 
> 

It seems that this is not normal.
The only things I have done with this account (created yesterday evening):
- created a test repo
- did some commits
- pushed to GitHub
- comments to issues of this project

**Comment by beardofedu** [comment]
All fixed 👍
