### ISSUE TITLE
Parking Lot

### ISSUE THREAD

**Issue by brianamarie** [githubschool/fra-14#9]
- [x] Where to store auth tokens in GitHub

Create a private/public key pair for whatever you are authenticating to. Try to avoid pushing any authentication to versioning.

**Comment by beardofedu** [comment]
- [ ] Branching strategy for a repo with long living branches for components, 1k+ branches

**Comment by beardofedu** [comment]
- [x] Force delete a branch with unmerged commits, where do they go?

Unmerged commits hangout in `reflog` will eventually be garbage collected, `-d` won't work but `-D` will

**Comment by brianamarie** [comment]
- [x] Egit - GitHub created resources
- [Webinar on Eclipse and GitHub](https://resources.github.com/webcasts/GitHub-and-Eclipse/)

**Comment by beardofedu** [comment]
- [ ] Search for a function being used by a subset of repositories within an org with 1,300+ repos ... the desired repos use labels

**Comment by beardofedu** [comment]
- [ ] Find a branch referencing a specific tag / what branch is the tag on? Is the dev using the latest from `master` or their branch

**Comment by beardofedu** [comment]
`PowerShell: for ($d=1; $d -le 6;$d++) { touch file$d.md; git add file$d.md; git commit -m "adding file$d.md";}` 

Doesn't work in Powershell since `touch` isn't supported
